name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: login to ghcr.io
        run: echo "${{ secrets.GH_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GH_USERNAME }}" --password-stdin
      - name: build image for github packages
        run: |
          docker buildx build --push \
            --tag ghcr.io/diffusehyperion/map-pinger:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
